# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/TinyTorch/',
                'doc_host': 'https://tinytorch.github.io',
                'git_url': 'https://github.com/tinytorch/TinyTorch/',
                'lib_path': 'tinytorch'},
  'syms': { 'tinytorch.core.utils': { 'tinytorch.core.utils.SystemInfo': ('setup/setup_dev.html#systeminfo', 'tinytorch/core/utils.py'),
                                      'tinytorch.core.utils.SystemInfo.__init__': ( 'setup/setup_dev.html#systeminfo.__init__',
                                                                                    'tinytorch/core/utils.py'),
                                      'tinytorch.core.utils.SystemInfo.__str__': ( 'setup/setup_dev.html#systeminfo.__str__',
                                                                                   'tinytorch/core/utils.py'),
                                      'tinytorch.core.utils.SystemInfo.is_compatible': ( 'setup/setup_dev.html#systeminfo.is_compatible',
                                                                                         'tinytorch/core/utils.py'),
                                      'tinytorch.core.utils.add_numbers': ('setup/setup_dev.html#add_numbers', 'tinytorch/core/utils.py'),
                                      'tinytorch.core.utils.hello_tinytorch': ( 'setup/setup_dev.html#hello_tinytorch',
                                                                                'tinytorch/core/utils.py')}}}
