# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/TinyTorch/',
                'doc_host': 'https://tinytorch.github.io',
                'git_url': 'https://github.com/tinytorch/TinyTorch/',
                'lib_path': 'tinytorch'},
  'syms': { 'tinytorch.core.utils': { 'tinytorch.core.utils.format_tensor_shape': ( 'setup.html#format_tensor_shape',
                                                                                    'tinytorch/core/utils.py'),
                                      'tinytorch.core.utils.hello_tinytorch': ('setup.html#hello_tinytorch', 'tinytorch/core/utils.py'),
                                      'tinytorch.core.utils.validate_tensor_shapes': ( 'setup.html#validate_tensor_shapes',
                                                                                       'tinytorch/core/utils.py')}}}
